---
title: "ResearchQ"
author: "Andrew Eross, Owen Wassel, Jack Messina, Khang Le"
date: "2025-11-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Front Matter

```{r}
remove(list = ls())
library(readxl)
library(dplyr)
library(class)
library(randomForest) 
library(xgboost)
library(caret)
library(ggplot2)
```

## Read in Datasets

```{r}
CODGameModes <- read.csv("~/Documents/GitHub/stat380finalproject/CODGameModes.csv")
CODGames1 <- read.csv("~/Documents/GitHub/stat380finalproject/CODGames_p1_380.csv")
CODGames2 <- read.csv("~/Documents/GitHub/stat380finalproject/CODGames_p2_380.csv")
```

## Research Question: Which classification method best predicts match outcome (win vs. loss) using gameplay statistics and match characteristics?

### Classification Methods Used: XGBoost; kNN; Random Forest

## Data Wrangling


## Model 1: kNN
```{r}

```

## Model 2: Random Forest
### Combine Data
```{r}
CODGames <- bind_rows(CODGames1 %>% mutate(Player = "Player1"),
                       CODGames2 %>% mutate(Player = "Player2"))
```

### Determine Win/Loss
```{r}
CODGamesResults <- CODGames %>% 
  extract(Result, into = c('TeamScore', 'OppScore'), regex = '([0-9]*)-([0-9]*)') %>%
  mutate(Outcome = as.factor(ifelse(as.numeric(TeamScore) > as.numeric(OppScore), "Win", "Loss"))) %>% 
  select(Eliminations, Deaths, Damage, Outcome) %>% 
  drop_na()
```

### Train/Test Split
```{r}
set.seed(1103)
inds <- sample(1:nrow(CODGamesResults), floor(.8*nrow(CODGamesResults)))
set.seed(NULL)

Train <- CODGamesScaled[inds, ]
Test <- CODGamesScaled[-inds, ]
```
```{r}
rf_model <- randomForest(Outcome ~ ., data = Train)
rf_preds <- predict(rf_model, Test)
confusionMatrix(rf_preds, Test$Outcome)
```

## Model 3: XGBoost
```{r}


```



